#pragma once

#define ERR_FM_GENERICERR			10

#define ERR_FM_CANNOTOPENDB			100
#define ERR_FM_ROOTGROUPNOTFOUND	101
#define ERR_FM_DBERROR				102
#define ERR_FM_FEEDGROUPNOTFOUND	103
#define ERR_FM_ERRSAVEFEED			104
#define ERR_FM_ERRSAVEFEEDGROUP		105
#define ERR_FM_NEWSFEEDNOTFOUND		107


#define ERR_NFP_INVALIDNEWSFEED		200