// http://sqlite.org/compile.html#omitfeatures

#define SQLITE_OMIT_AUTHORIZATION
#define SQLITE_OMIT_AUTOVACUUM
#define SQLITE_OMIT_BETWEEN_OPTIMIZATION
#define SQLITE_OMIT_BUILTIN_TEST
#define SQLITE_OMIT_CAST
#define SQLITE_OMIT_CHECK
#define SQLITE_OMIT_COMPLETE
#define SQLITE_OMIT_COMPILEOPTION_DIAGS
#define SQLITE_OMIT_COMPOUND_SELECT
#define SQLITE_OMIT_CONFLICT_CLAUSE
//#define SQLITE_OMIT_DATETIME_FUNCS // set by SQLITE_OMIT_FLOATING_POINT
#define SQLITE_OMIT_DEPRECATED
#define SQLITE_OMIT_EXPLAIN
#define SQLITE_OMIT_FLAG_PRAGMAS
#define SQLITE_OMIT_FLOATING_POINT
#define SQLITE_OMIT_FOREIGN_KEY
#define SQLITE_OMIT_INCRBLOB
#define SQLITE_OMIT_INTEGRITY_CHECK
#define SQLITE_OMIT_LOAD_EXTENSION
#define SQLITE_OMIT_MEMORYDB
#define SQLITE_OMIT_PAGER_PRAGMAS
#define SQLITE_OMIT_PROGRESS_CALLBACK
#define SQLITE_OMIT_SCHEMA_PRAGMAS
#define SQLITE_OMIT_SCHEMA_VERSION_PRAGMAS
#define SQLITE_OMIT_TCL_VARIABLE
#define SQLITE_OMIT_TEMPDB
//#define SQLITE_OMIT_TRACE // set by SQLITE_OMIT_FLOATING_POINT
#define SQLITE_OMIT_TRUNCATE_OPTIMIZATION
#define SQLITE_OMIT_XFER_OPT

#define SQLITE_HAVE_ISNAN

#define SQLITE_DIRECT_OVERFLOW_READ
#define SQLITE_DEFAULT_MEMSTATUS 0

#define SQLITE_OMIT_AUTORESET
#define SQLITE_OMIT_BLOB_LITERAL



