//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Main.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_TREE_HEADER                 129
#define IDR_UPDATENEWMSG                129
#define ID_PROGRESS                     130
#define IDS_ADDCHANNELWIZARD            131
#define IDS_CHANNELPROPERITES           132
#define IDS_CHANNELPROPERTIES           132
#define ID_RSS_INDICATOR                133
#define IDS_GREATNEWS_HOME              134
#define ID_POPUP_INDICATOR              135
#define IDS_CREDIT                      136
#define IDS_OPENEXISTINGCHANNEL         137
#define IDS_SUBSCRIIBECHANNEL           138
#define IDS_GROUPITEMS                  139
#define IDS_CHANNELITEMS                140
#define IDS_ITEMSBEFORECLEANUP          141
#define IDS_ITEMSAFTERCLEANUP           142
#define IDS_CLEANINGCHANNEL             143
#define IDS_COMPACTINGDATAFILE          144
#define IDS_CLEANUPFINISH               145
#define IDS_SELECTONECHANNEL            146
#define IDS_FILLINSEARCHKEYWORD         147
#define IDS_NAMESEARCH                  148
#define IDS_EXPORTRSSSUMMARY            149
#define IDS_SPECIFYOUTPUT               150
#define IDS_EXPORTSUMMARY               151
#define IDS_CONFIRMDELGROUP             152
#define IDS_CONFIRMDELCHANNEL           153
#define IDS_CONFIRMDELWATCH             154
#define IDS_CONFIRMDELLABEL             155
#define IDS_DATAFILENOTFOUND            156
#define IDS_INCOMPATFILE                157
#define IDS_NEWVERSION                  158
#define IDS_CHANNELCOUNT                159
#define IDS_UPDATESUMMARY               160
#define IDS_UPDATEFAILEDCOUNT           161
#define IDS_FINISHUPDATE                162
#define IDS_UPDATESTATUS                163
#define IDS_CONFIRMCLEANUP              164
#define IDS_CONFIRMDELSELECTEDCHANNEL   165
#define IDS_SEARCHSTATUS                166
#define IDS_UPDATING                    167
#define IDS_FILLINURL                   168
#define IDS_EMPTYCHANNELTITLE           169
#define IDS_SEARCHNOTFOUND              170
#define IDS_PLSSELECTGROUP              171
#define IDS_SPECIFYFILENAME             172
#define IDS_SPECIFYURL                  173
#define IDS_STOPIMPORT                  174
#define IDS_USINGLATEST                 175
#define IDS_FAILEDCHECKING              176
#define IDS_EMPTYNEWSLIST               177
#define IDS_NOUNREADCHANNEL             178
#define IDS_SELECTCHANNELTOMOVE         179
#define IDS_SELECTGRPTOMOVEIN           180
#define IDS_SELECTCHANNELTODEL          181
#define IDS_SELECTCHANNELTODETACH       182
#define IDS_FILLINBLOGLINESACNT         183
#define IDS_PWDMISMATCH                 184
#define IDS_FILLINMATCHWORD             185
#define IDS_FILLINWATCHTITLE            186
#define IDS_SELECTONEWATCHOPTION        187
#define IDS_SAMECOLOR                   188
#define IDS_SELECTONECHANNELTOWATCH     189
#define IDS_IMPORTSUMMARY               190
#define IDS_IMPORTSKIP                  191
#define IDS_IMPORTFAILEDSUMMARY         192
#define IDS_IMPORTGROUPOK               193
#define IDS_IMPORTSKIPGRP               194
#define IDS_IMPORTGROUPFAILED           195
#define IDS_IMPORTSKIPFEED              196
#define IDS_IMPORTINGFEED               197
#define IDS_IMPORTRENAME                198
#define IDS_IMPORTFEEDOK                199
#define IDS_IMPORTFEEDFAILED            200
#define IDR_TREEMENU_ROOT               201
#define IDS_IMPORTFEEDFAILED0           201
#define IDR_TREEMENU_GROUP              202
#define IDD_FEED_GROUP                  202
#define IDS_DIDNOTSHUTDOWNPROPERLY      202
#define IDR_TREEMENU_FEED               203
#define IDR_TREEMENU_CHANNEL            203
#define IDS_NUMOFITEMSWITHLABEL         203
#define IDB_TREE                        204
#define IDS_CLEANLABELLED               204
#define IDB_LIST                        205
#define IDS_REPLACEYOURSITE             205
#define IDR_NAVIBAR                     206
#define IDR_TRAYPOPUP                   206
#define IDS_NOITEMFOUNDINSEARCH         206
#define IDS_SUREMARKALLASREAD           207
#define IDS_CANTFINDBLOGTOOL            208
#define IDD_OPTION_GENERAL              209
#define IDS_UPDATETONEWVERSION          209
#define IDR_TREEMENU_WATCHROOT          211
#define IDR_TREEMENU_WATCH              212
#define IDD_WATCH_NAME                  213
#define IDD_WATCH_CHANNELS              215
#define IDD_CLEANUP_DAYS                218
#define IDD_CLEANUP_CHANNELS            219
#define IDD_CLEANUP_PROGRESS            220
#define IDD_IMPORT                      224
#define IDR_MENU1                       224
#define IDR_PLACEHOLDER                 224
#define IDD_IMPORT_FILE                 224
#define IDR_ADDRESSBAR                  225
#define IDR_FILTERBAR                   227
#define IDR_MAINREGISTRY                227
#define IDD_OPTION_PAGE                 229
#define IDD_CHANNEL_URL                 230
#define IDD_CHANNEL_PROPERTIES          231
#define IDD_CHANNEL_GROUP               232
#define IDD_IMPORT_SELECT               233
#define IDR_FINDBAR                     233
#define IDD_IMPORT_PROGRESS             234
#define IDR_NEWSLIST_POPUP              235
#define IDD_SEARCHING                   237
#define IDD_LABEL                       238
#define IDR_TREEMENU_LABELROOT          239
#define IDD_EXPORT_FILE                 239
#define IDR_TREEMENU_LABEL              240
#define IDD_EXPORT_SELECT               240
#define IDD_OPTION_USABILITY            241
#define IDR_TREEMENU_DEFAULT            241
#define IDB_STANDARDBAR                 242
#define IDB_RSS                         244
#define IDB_BLOCKPOPUP                  245
#define IDR_FAVI_POPUP                  246
#define IDD_SEARCHCHANNEL               247
#define IDR_TREEMENU_CHANNEL_ADV        247
#define IDD_EXPORTRSS                   248
#define IDD_FINDCHANNEL                 249
#define IDD_ORGANIZE_CHANNELS           250
#define IDD_IMPORT_GROUP                251
#define IDB_ABOUT                       253
#define IDD_SYNC_ACCOUNT                254
#define IDD_SYNC_CHANNELS               255
#define IDD_OPTION_FEATURES             256
#define IDB_HEADER                      257
#define IDB_BROWSERSTATUS               261
#define IDD_CONFIGBLOGTHIS              262
#define IDD_OPTION_CONNECTION           264
#define IDD_CHANNEL_SETTINGS            265
#define IDD_DINOSAURCHANNELS            266
#define IDD_STATCONFIG                  267
#define IDD_SELECTCHANNEL               271
#define IDD_GLOBALSEARCH                272
#define IDC_GROUP_NAME                  1000
#define IDC_GROUP_DESC                  1001
#define IDC_CREDIT                      1001
#define IDC_SYNC_PASSWORD               1001
#define IDC_EDTNEWITEMNOTIFYSECONDS     1001
#define IDC_TXTLOGINNAME                1001
#define IDC_URL                         1002
#define IDC_WATCH_WORDS                 1002
#define IDC_TXTFILENAME                 1002
#define IDC_EDTURL                      1002
#define IDC_LABEL_NAME                  1002
#define IDC_KEYWORD                     1002
#define IDC_GROUP_WEBSITE               1002
#define IDC_FILENAME                    1002
#define IDC_SYNC_ACCOUNT                1002
#define IDC_TOOLNAME                    1002
#define IDC_PROXY_URL                   1002
#define IDC_EDTCLEANUPITEM              1002
#define IDC_DINOSOURDAYS                1002
#define IDC_EDITNUMOFCHANNELS           1002
#define IDC_ENCLOSURE                   1002
#define IDC_KEYWORDS                    1002
#define IDC_QUERY                       1003
#define IDQUERY                         1003
#define IDC_NAME                        1003
#define IDC_URL2                        1003
#define IDC_TOOLURL                     1003
#define IDC_PROXY_PORT                  1003
#define IDC_AUTHENTICATION              1004
#define IDC_PROXY_USER                  1004
#define IDC_CONTACTS                    1004
#define IDC_SYNC_CONFIRM_PASSWORD       1005
#define IDC_PROXY_PASSWORD              1005
#define IDC_TXTLOGINPWD                 1005
#define IDC_BLOCKPOPUP                  1006
#define IDC_CHKCOMPRESS                 1006
#define IDC_NOTIFYNEWITEMS              1006
#define IDC_PROXY_BYPASS                1006
#define IDC_NOTIFYINACTIVECHANNELS      1006
#define IDC_CHKWATCHURL                 1006
#define IDC_TRACKCOMMENTS               1006
#define IDC_CHKREQUIRELOGIN             1006
#define IDC_DESCRIPTION                 1007
#define IDC_SHOW_UPDATEFINISH_TOOLTIPs  1007
#define IDC_SHOWWELCOME                 1007
#define IDC_KEEPINACTIVE                1007
#define IDC_TITLE                       1008
#define IDC_FORMAT                      1009
#define IDC_UPDATECHANNELATSTARTUP      1010
#define IDC_CHKTITLE                    1010
#define IDC_WEBSITE                     1010
#define IDC_CHKDELETEUNREAD             1010
#define IDC_BTNBROWSE                   1010
#define IDC_CHKALLWORDS                 1010
#define IDC_CHKQUERYCHANNEL             1010
#define IDC_UPDATE                      1010
#define IDC_CHKEXPORTWATCHLABEL         1010
#define IDC_CHKCLOSENEWSLIST            1010
#define IDC_AUTOUPDATECHANNEL           1010
#define IDC_DONTMARKBLOGLINESREAD       1010
#define IDC_LABELTHIS                   1010
#define IDC_CHKEXCLUDEDISABLED          1010
#define IDC_CHKDELETEMARKED             1011
#define IDC_AUTOUPDATE_FREQ             1011
#define IDC_CBOIMPORTURL                1011
#define IDC_TXTURL                      1011
#define IDC_CHKIMPORTWATCHLABEL         1011
#define IDC_CHKSETFILTERTOUNREAD        1011
#define IDC_SEARCHCHANNEL               1011
#define IDC_COMBOGROUP                  1011
#define IDC_MARKCHANNELREADWHENSWITCHING 1011
#define IDC_UPDATE_FREQ                 1011
#define IDC_EMAILTHIS                   1011
#define IDC_TOOLTYPES                   1011
#define IDC_CLEANUPREMIND               1012
#define IDC_CLEANUPREMINDER             1012
#define IDC_MARK_LASTCHANNEL_READ       1012
#define IDC_DELICIOUS                   1012
#define IDC_UPDATE_FREQ2                1012
#define IDC_CHKAUTHOR                   1013
#define IDC_CHKWHOLE                    1013
#define IDC_REMOVEFROMTASKBAR           1013
#define IDC_SEARCH_OPEN_NEWSLIST        1013
#define IDC_ARTHUR                      1013
#define IDC_CHKCLEANUPITEM              1013
#define IDC_FURL                        1014
#define IDC_LSTCHANNELS                 1015
#define IDC_LSTPROGRESS                 1015
#define IDC_CHKAUTHOR2                  1015
#define IDC_BLOGTHIS                    1015
#define IDC_TOOLSLIST                   1015
#define IDC_DINOSAURLIST                1015
#define IDC_LISTCHANNEL                 1015
#define IDC_DESELECTALL                 1016
#define IDC_BTNSELECTALL                1016
#define IDC_STOP                        1016
#define IDC_VALIDATE                    1016
#define IDC_TEXTCOLOR                   1016
#define IDC_ASSIGNGROUP                 1016
#define IDC_NEWGROUP                    1016
#define IDC_BTNDEFAULTREADER            1016
#define IDC_CONFIGBLOGTHIS              1016
#define IDC_BTNDELETEINACTIVE           1016
#define IDC_CHKALLCHANNELS              1017
#define IDC_BKCOLOR                     1017
#define IDC_BTNSELECTALL2               1017
#define IDC_NEW                         1017
#define IDC_HIGHLIGHTNEWSWATCH          1017
#define IDC_CHECKEXISINGNEWS            1018
#define IDC_SAVE                        1018
#define IDC_CHKCONTENT                  1019
#define IDC_WATCH_NAME                  1020
#define IDC_LASTUPDATE                  1021
#define IDC_CBODAYS                     1022
#define IDC_LASTMODIFIED                1022
#define IDC_RDOALL                      1023
#define IDC_CLEANPROGRESS               1024
#define IDC_RDOSELECTIVE                1024
#define IDC_CLEANTEXT                   1025
#define IDC_LISTCHANNELS                1026
#define IDC_IMPORTING                   1026
#define IDC_LISTCHANNELS2               1026
#define IDC_CHKCASE                     1027
#define IDC_TXTNUMOFITEMS               1028
#define IDC_LANGUAGE                    1029
#define IDC_ITEM_READ_SECONDS           1029
#define IDC_CHKDISABLE                  1030
#define IDC_CHANNEL_READ_SECONDS        1030
#define IDC_GROUPTREE                   1031
#define IDC_FEEDTREE                    1031
#define IDC_RDOIMPORTWELLKNOWN          1032
#define IDC_RDOIMPORTSELECTED           1033
#define IDC_TREEGROUP                   1033
#define IDC_RDOIMPORTSELECTFILE         1035
#define IDC_RDOIMPORTALL                1036
#define IDC_RDOIMPORTINTERNET           1036
#define IDC_BTNUNSELECTALL              1038
#define IDC_PROGRESS                    1039
#define IDC_SEARCH                      1040
#define IDC_CHKNOUPDATE                 1041
#define IDC_CHKDISABLEWATCH             1041
#define IDC_RDOANY                      1044
#define IDC_UNSELECTALL                 1045
#define IDC_RDOEXACT                    1046
#define IDC_TREESELECT                  1046
#define IDC_BUILDNUM                    1048
#define IDC_DBVER                       1049
#define IDC_NUMOFITEM                   1049
#define IDC_LINE                        1051
#define IDC_LINE1                       1051
#define IDC_DELETECHANNELS              1052
#define IDC_LINE2                       1053
#define IDC_LINE3                       1054
#define IDC_MIDDLECLICK                 1056
#define IDC_ABOUTIMAGE                  1057
#define IDC_DELETE                      1057
#define IDC_IGNORE                      1057
#define IDC_OPENRSSLINK                 1057
#define IDC_SHOWLABEL                   1057
#define IDC_CLICKTODEFAULTBROWSER       1058
#define IDC_MARKREADDIRECTLY            1058
#define IDC_CHKCLOSETOTRAY              1058
#define IDC_CHKNOFEEDBURNER             1058
#define IDC_CHKKEEPORIGINALLINK         1058
#define IDC_HIGHLIGHT                   1059
#define IDC_DISABLETAB                  1059
#define IDC_SHOWWATCH                   1059
#define IDC_GRAPHIC                     1060
#define IDC_EXTERNALBROWSER             1060
#define IDC_ADD_GROUP                   1061
#define IDC_RSSINNEWTAB                 1061
#define IDC_SHOWBLANKSCREEN             1062
#define IDC_STAYONSAMEPAGE              1062
#define IDC_USE_IE_PROXY                1062
#define IDC_RDOEXTERNALBROWSER          1062
#define IDC_SHOWTOP10                   1063
#define IDC_GN_PROXY                    1063
#define IDC_RDOREADINGPANE              1063
#define IDC_DETACHBLOGLINES             1064
#define IDC_RDOREADINGPANE2             1064
#define IDC_SYNCBLOGLINES               1065
#define IDC_BEFORECLEANUP               1066
#define IDC_AFTERCLEANUP                1067
#define IDC_GOTONEXTCHANNELGROUP        1067
#define IDC_MARKREADAUTOMATICALLY       1068
#define IDC_MARKREADINTERACTIVELY       1069
#define IDS_GROUPNAME                   1070
#define IDS_DESC                        1071
#define IDS_WEBSITE                     1072
#define IDS_STARTS                      1073
#define IDS_UPDATECHANNELEVERY          1074
#define IDS_REMINDCLEANUPEVERY          1075
#define IDS_DISPLAY                     1076
#define IDS_ITEMPERPAGE                 1077
#define IDS_CLICKNEXT                   1078
#define IDS_MARKREAD                    1079
#define IDS_MARKREADSEC                 1080
#define IDS_OPENFUNCTION                1081
#define IDS_ITEMFUNCTION                1082
#define IDS_LABEL                       1083
#define IDS_SELECTCHANNEL               1084
#define IDS_CHANNELURL                  1085
#define IDS_CHANNELTITLE                1086
#define IDS_CHANNELDESC                 1087
#define IDS_HOMEPAGE                    1088
#define IDS_CHANNELFORMAT               1089
#define IDS_LASTUPDATE                  1090
#define IDS_SELECTGROUP                 1091
#define IDS_TTL                         1091
#define IDS_WATCHNAME                   1092
#define IDS_LASTMODIFIED                1092
#define IDS_WATCHWORDS                  1093
#define IDS_FORMATCHEDITEMS             1094
#define IDS_BACKGROUND                  1095
#define IDS_EXPORTFILENAME              1096
#define IDS_SELECTCHANNELGROUP          1097
#define IDS_WARNING                     1098
#define IDS_FILENAME                    1099
#define IDS_URL                         1100
#define IDS_MOVEINTOGROUP               1101
#define IDS_STOPMSG                     1102
#define IDS_TIP                         1103
#define IDS_SELECT                      1104
#define IDS_DELETENEWS                  1105
#define IDS_SEARCHFROM                  1106
#define IDS_KEYWORD                     1107
#define IDS_NAME                        1108
#define IDS_BLOGLINESACNT               1109
#define IDS_BPASSWORD                   1110
#define IDS_BCONFIRMPWD                 1111
#define IDS_SELECTBLOGLINESCHANNELS     1112
#define IDC_AUTOUPDATE_TITLE            1114
#define IDC_CLEANUPOLD                  1115
#define IDC_CBOCLEANUP                  1116
#define IDC_CLEANUPOVERRIDE             1117
#define IDC_TXT_TTL                     1118
#define IDC_CBOSTYLES                   1119
#define IDC_STYLE                       1120
#define IDC_BTNKEEPINACTIVE             1122
#define IDC_DONTCOLLAPSEGROUP           1123
#define IDC_CHKDELETTEMP                1124
#define IDC_HINT                        1125
#define IDC_NUMOFITEMS                  1127
#define IDC_LOGINNAME                   1130
#define IDC_LOGINPWD                    1131
#define IDC_ITEMS                       1132
#define IDC_INACTIVENOTE                1133
#define IDC_SEARCHALLCHANNELFOR         1134
#define IDC_INACTIVEDAYS                1135
#define IDC_NEWSITEMPOPUPSTAYS          1136
#define IDC_NEWITEMPOPUPSECONDS         1137
#define IDC_DOUBLECLICKNEWSLIST         1138
#define IDC_CLICKLINKINREADINGPANE      1139
#define IDC_SHOWFEATURES                1140
#define IDC_PODCASTINGENCLOSURE         1141
#define IDC_CONFIGEDTOOLS               1142
#define IDC_TOOLDETAILS                 1143
#define IDS_TYPE                        1145
#define IDC_TIPS                        1146
#define IDC_PROXYURL                    1147
#define IDC_PROXYPORT                   1148
#define IDC_PROXYNAME                   1149
#define IDC_PROXYPWD                    1150
#define IDC_SKIPPROXY                   1151
#define IDC_ITEMPERCHANNEL              1152
#define IDC_OVERRIDEATCHANNEL           1153
#define IDC_WHATTOWATCH                 1154
#define IDC_ALLLABELS                   1155
#define IDC_ALLWATCHES                  1156
#define IDC_DELTEMPWHENEXIT             1157
#define IDC_MARKCHANGEDUNREAD           1158
#define ID_IE_STOP                      32774
#define ID_TREEMENU_MARKASUNREAD        32777
#define ID_CHANNEL_UPDATEALLCHANNEL     32791
#define ID_CHANNEL_UPDATE               32792
#define ID_CHANNEL_MARKALLASREAD        32793
#define ID_CHANNEL_ADDGROUP             32796
#define ID_CHANNEL_ADDCHANNEL           32797
#define ID_CHANNEL_PROPERTIES           32799
#define ID_CHANNEL_DELETE               32800
#define ID_IE_FORWARD                   32803
#define ID_IE_REFRESH                   32805
#define ID_IE_BACK                      32806
#define ID_TOOLS_IMPORT                 32808
#define ID_VIEW_MAXIMIZEBROWSER         32811
#define ID_TREEMENU_EXPANDALL           32815
#define ID_TREEMENU_COLLAPSEALL         32816
#define ID_CHANNEL_MARKASREAD           32818
#define ID_CHANNEL_MARKASUNREAD         32819
#define ID_VIEW_BROWSERATRIGHT          32827
#define ID_VIEW_BROWSERATBOTTOM         32828
#define ID_WATCHROOT_REFRESH            32835
#define ID_TREEMENU_ADDNEWSWATCH        32837
#define ID_IE_HOME                      32838
#define ID_IE_FAVI                      32839
#define ID_IE_STYLE                     32840
#define ID_TOOLS_CLEANUP                32841
#define ID_TOOLS_EXPORT                 32842
#define ID_ADDRESS_PLACEHOLDER_COMBO    32846
#define ID_ADDRESS_GO                   32847
#define ID_FILTER_PLACEHOLDER_DAY       32848
#define ID_FILTER_PLACEHOLDER_STATUS    32849
#define ID_FILTER_SHOWALL               32850
#define ID_TOOLS_OPTIONS                32852
#define ID_IE_NAVIGATEXML               32854
#define ID_EDIT_FINDNEXT                32858
#define ID_FIND_COMBO                   32859
#define ID_IE_PREV                      32860
#define ID_IE_NEXT                      32861
#define ID_NEWSLIST_MARKASUNREAD        32865
#define ID_NEWSLIST_MARKALLASUNREAD     32867
#define ID_NEWSLIST_                    32868
#define ID_NEWSLIST_TOGGLEREAD          32870
#define ID_NEWSLIST_TOGGLEPIN           32872
#define ID_IE_SETSTATUSTEXT             32874
#define CMD_ID_REFRESH                  32876
#define CMD_ID_READFLAGCHANGED          32878
#define CMD_ID_NEWSITEMSELECTED         32880
#define ID_IE_STYLE_FIRST               32884
#define ID_IE_STYLE_LAST                32904
#define ID_FIND_GOOGLE                  32905
#define ID_FIND_GOOGLEGROUP             32906
#define ID_FIND_FEEDSTER                32907
#define ID_FIND_GOOGLE_LAST             32915
#define ID_FIND_NEXT                    32916
#define ID_EDIT_FINDNEWSITEM            32917
#define ID_VIEW_CHANNELBAR              32922
#define ID_VIEW_NEWSLIST                32923
#define ID_LABEL_ADD                    32925
#define ID_LABEL_DELETE                 32927
#define ID_LABEL_TAGGLE_FIRST           32928
#define ID_LABEL_TAGGLE_LAST            33028
#define ID_ALL_ID                       33029
#define CMD_ID_LOADINITDATA             33031
#define ID_TREEMENU_COLLAPSETOGROUP     33033
#define ID_VIEW_NEXTUNREADNEWS          33035
#define ID_IE_FOUNDFEEDS                33047
#define ID_IE_RSSICON_CLICKED           33049
#define ID_IE_RSSFEED_FIRST             33050
#define ID_IE_RSSFEED_LAST              33305
#define ID_TOOLS_CHANNELSTATISTICS      33306
#define ID_TOOLS_MOST10                 33312
#define ID_TOOLS_LEAST10                33313
#define ID_CHANNEL_ADD                  33314
#define ID_CMD_CMD                      33320
#define ID_CHANNEL_STOPALLUPDATES       33321
#define ID_IE_OPENCHANNEL               33322
#define ID_FAVI_ADDTOFAVORITES          33324
#define ID_FAVI_ORGANIZEFAVORITES       33325
#define ID_FAVI_FIRST                   33328
#define ID_FAVI_LAST                    36329
#define ID_IE_POPUPBLOCKED              36332
#define ID_IE_POPUPICON_CLICKED         36333
#define ID_IE_BLOCKEDPOPUP_FIRST        36334
#define ID_IE_BLOCKEDPOPUP_LAST         36535
#define ID_CHANNEL_ADDSEARCHCHANNEL     36537
#define ID_NEWSLIST_DELETE              36539
#define ID_TOOLS_EXPORTNEWSLIST         36543
#define ID_VIEW_NEXTUNREADGROUP         36544
#define ID_EDIT_FINDSUBSCRIPTEDCHANNEL  36547
#define ID_CHANNEL_ORGANIZECHANNELS     36548
#define ID_HELP_VISITGREATNEWS          36550
#define ID_IE_GOTO_PAGE                 36551
#define CMD_ID_MARKPAGEREAD             36555
#define ID_NEWSLIST_ADDNEWLABEL         36556
#define ID_CHANNEL_BLOGLINES            36558
#define CMD_ID_MARKITEMREAD             36559
#define ID_VIEW_PREVIOUSPAGE            36560
#define ID_VIEW_NEXTPAGE                36561
#define ID_VIEW_PREVPAGE                36563
#define ID_CHANNEL_REFRESH              36564
#define CMD_ID_FILTERCHANGE             36565
#define ID_HELP_VISITFORUM              36567
#define ID_VIEW_LANGUAGE0               36569
#define ID_VIEW_LANGUAGELAST            36600
#define ID_NEWSLIST_TOGGLEUNREAD        36601
#define ID_CHANNEL_CLEANUP              36604
#define CMD_ID_LABELITEM                36606
#define CMD_ID_REFRESHTAB               36608
#define ID_VIEW_NEWTAB                  36609
#define CMD_ID_EMAILITEM                36615
#define CMD_ID_ADDDELICIOUS             36616
#define CMD_ID_ADDFURL                  36617
#define CMD_ID_CONFIGBLOGTHIS           36624
#define CMD_ID_BLOGTHIS_POPUP           36625
#define CMD_ID_BLOGTHIS                 36627
#define CMD_ID_BLOGTHISTOOL0            36628
#define CMD_ID_BLOGTHISTOOL100          36728
#define ID_OPENGREATNEWS                36729
#define ID_TOOLS_MOSTACTIVE             36732
#define ID_TOOLS_LEASTACTIVE            36733
#define ID_TOOLS_CONFIGSTATISTICS       36735
#define CMD_ID_TRACKCOMMENTS            36737
#define ID_EDIT_GLOBALSEARCH            36738
#define ID_CHANNEL_RENAME               36739
#define CMD_ID_TOGGLEREADUNREAD         36743
#define ID_CHANNEL_MARKPAGEASREAD       36744
#define CMD_ID_SUBCHANNEL               36747
#define ID_CHANNEL_WORKOFFLINE          36748
#define ID_CHANNEL_                     36749
#define ID_CHANNEL_UNLABELALL           36751
#define CMD_ID_SETFOCUS_FEEDTREE        36753
#define CMD_ID_SETFOCUS_NEWSLIST        36755
#define CMD_ID_SHOWCHANNELWEBSITE       36760
#define ID_VIEW_READINGPANE             36761
#define ID_READINGPANE_BOTTOM           36762
#define ID_READINGPANE_RIGHT            36763

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        273
#define _APS_NEXT_COMMAND_VALUE         36764
#define _APS_NEXT_CONTROL_VALUE         1159
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
